### ISSUE TITLE
Too restrictive permission requirements (bigquery.jobs.create)

### ISSUE THREAD

**Issue by inkrement** [r-dbi/bigrquery#237]
I have access to a big query project (let's call it proj-x) and I am able to query a table using the web-interface (bigquery.cloud.google.com) so I should have all required permissions. 

But if I try to re-run the same query using bigrquery I get the following error:

> Error: Access Denied: Project proj-x: The user mymail@domain.name does not have bigquery.jobs.create permission in project proj-x.

Do I _really_ need those permissions to use bigrquery or is there a workaround?

**Comment by ras44** [comment]
Hoping my input is helpful: you do need jobs create permissions in the project because bigrquery will create a job and then query the status of the job until it is complete before returning query results.  An exampe of this is shown in the source:

https://github.com/r-dbi/bigrquery/blob/700990c0bba8b190dfa6f69ce264d4b986ee56ef/R/bq-query.R#L46-L60

I believe this shouldn't be an issue with bigrquery since bigrquery is returning the response correctly from the API and not making any permissions-related decisions.   And admin can adjust the permissions for the project in https://console.cloud.google.com/iam-admin/iam, choosing your userid, and setting `role` to `BigQuery Job User`.
