### ISSUE TITLE
Feature to upload dataframe with a list-type column

### ISSUE THREAD

**Issue by ldanai** [r-dbi/bigrquery#256]
I would like to be able to upload dataframe with a list-type column to bigquery. 

===========
a
A tibble: 3 x 2
  hour  list_hour        
  <chr> <list>           
1 H9    <tibble [24 x 2]>
2 H9    <tibble [24 x 2]>
3 H9    <tibble [24 x 2]>

a$list_hour[1]
[[1]]
A tibble: 24 x 2
   name  value
   <chr> <int>
 1 H0       56
 2 H1       55
 3 H2       55
 4 H3       60
 5 H4       66
 6 H5       63
 7 H6       55
 8 H7       71
 9 H8       50
10 H9       35
... with 14 more rows

job = insert_upload_job(project = "xxxxxxx", 
                                       dataset = "xxxxxx", 
                                       table   = "xxxxx",
                                       value   = a,
                                       create_disposition = "CREATE_IF_NEEDED",
                                       write_disposition  = "WRITE_TRUNCATE")
Error: Unsupported type: list

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by hadley** [comment]
The problem is that you're using the old API. This works for me:

```R
library(bigrquery)

df <- tibble::tibble(x = 1:3, y = list(1, 1:2, 1:3))
tb <- bq_table(bq_test_dataset(), "listcol")

bq_table_upload(tb, df)
bq_table_download(tb)
```

**Comment by ldanai** [comment]
Thank you!!! It works. I now learned how to use reprex, very helpful :)
