### ISSUE TITLE
Error in pb_tick(self, private, len, tokens) : !self$finished is not TRUE 

### ISSUE THREAD

**Issue by jberninger** [r-dbi/bigrquery#269]
Hey, when trying to pull larger datasets from my GBQ account, I hit this error message:
"Error in pb_tick(self, private, len, tokens) : !self$finished is not TRUE "

The table I am querying is ~105GB and the same SQL query works fine in the GBQ console. It's not a very complex query, just asking for 200MB of data. Query below. I can't find anything related to this error message, hoping y'all can help out

R code:
`library(bigrquery)
project_id <- "xxx-xxx-xxx" # put your project ID here
sql <- "SELECT
  *
FROM
`xxx-xxx-xxx.Conversion_Records.Conversion_records_2018_9_to_10`
WHERE event_time >= '2018-09-16 00:00:01'
AND lower(campaign_name) like 'camp_a%'
AND lower(vendor_name) = 'vendor_a';"

gbq <- query_exec(sql, project = project_id, use_legacy_sql = FALSE, max_pages = Inf)
`

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by bokov** [comment]
Possible workaround:

https://github.com/mikajoh/stmprinter/issues/2#issuecomment-2583192343
