### ISSUE TITLE
'Unknown type GEOGRAPHY' when fetching GIS data.

### ISSUE THREAD

**Issue by stelsemeyer** [r-dbi/bigrquery#313]
I have trouble fetching geographical data from BigQuery, produced by functions like `ST_GEOGFROMTEXT`:

```
library(bigrquery)
billing <- bq_test_project()
sql <- "SELECT ST_GEOGFROMTEXT('POINT(15 20)') AS geog"
tb <- bq_project_query(billing, sql)
data <- bq_table_download(tb)
```
errors out with
```
Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  : 
Unknown type GEOGRAPHY
````
<sup>(unfortunately I could not get this code rendered with reprex.)</sup>

Is there any way to coerce those data types to strings/character by default? I saw that `readr` is doing some type detection in the background.

**Comment by geoffreylarnold** [comment]
So the way I've handled this is done the SQL differently and then converted to an sf object once the data is in R.

```
library(bigrquery)
library(sf)
billing <- bq_test_project()
sql <- "SELECT ST_ASTEXT(ST_GEOGFROMTEXT('POINT(15 20)')) AS geog"
tb <- bq_project_query(billing, sql)
data <- bq_table_download(tb) %>%  
     st_as_sf(wkt = "geog")
```

**Comment by Tartomas** [comment]
Hello, I have a similar issue and I would like to resolve it using dplyr in order to get the show_quey() and then translate it to SQL. But when I can't get rid of the "geometry" field neither call it to my environment like this: 

`
data = tbl(con, "data") %>% 
    select(-location)
data
Complete
Billed: 0 B
Downloading 11 rows in 1 pages.
Error in bq_parse_files(schema_path, page_paths, n = page_info$n_rows,  : 
  Unknown type GEOGRAPHY
`
Do you know how to resolve this? 
Thanks!

**Comment by denironyx** [comment]
Hey @Tartomas, did you find a solution to the comment you made?? I am kinda in a similar pitfall at the moment.

**Comment by hadley** [comment]
bigrquery doesn't currently support GEOMETRY columns, sorry.

**Comment by chrowe** [comment]
> bigrquery doesn't currently support GEOMETRY columns, sorry.

Has this changed or is https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#geography_type something different?

**Comment by denironyx** [comment]
Nope, it is still the same.
