### ISSUE TITLE
Cannot authenticate through GCP Instance

### ISSUE THREAD

**Issue by ArbenKqiku** [r-dbi/bigrquery#363]
Hello,

First of all, thank you for this great package!

**Here are the steps that I have taken so far locally on my RStudio console**:

1) get the token through gargle and save it as an RDS file
`# get token via gargle
library(gargle)
token <- token_fetch(scopes = "https://www.googleapis.com/auth/bigquery", path = "/home/arben/Scripts/BigQuery/keyscarab-xxxxxxxxxxxxxxx.json") # 
saveRDS(token, file = "bigQueryToken2.RDS") # save it so that you can retrieve it later`

2) Authenticate through the previously saved RDS file
`library(bigrquery)
bq_auth(token = readRDS("/Users/arbenkqiku/Desktop/Scripts/bigQueryToken2.RDS"))`

With this, I can authenticate and manipulate tables on BigQuery.

**Here are the steps that I have taken on GCP**:
1) Launch an R session on GCP terminal
2) Try to authenticate through the locally create RDS token
`library(bigrquery)
bq_auth(token = readRDS("/home/arben/Scripts/bigQueryToken2.RDS"))`

Here is the error message that I get:
`Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://accounts.google.com/o/oauth2/auth?client_id=`

As I am in the terminal nothing opens in the browser. 

I have also tried to fetch the token directly from the terminal:

`token <- token_fetch(scopes = "https://www.googleapis.com/auth/bigquery", path = "/home/arben/Scripts/BigQuery/keyscarab-xxxxxxxxxxxxxxxx.json")`

I get the same error message as displayed above. 

If I read the token as an RDS file, it seems that the token is fine:

`> token = readRDS("/home/arben/Scripts/bigQueryToken.RDS")
> token
<Token (via gargle)>
  <oauth_endpoint> google
             <app> gargle-calliope
           <email> arben@comtogether.com
          <scopes> ...bigquery, ...userinfo.email
     <credentials> access_token, expires_in, refresh_token, scope, token_type, id_token
---
> token$credentials
$access_token
[1] "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
$expires_in
[1] 3600
$refresh_token
[1] "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
$scope
[1] "https://www.googleapis.com/auth/bigquery https://www.googleapis.com/auth/userinfo.email openid"
$token_type
[1] "Bearer"
$id_token
[1] "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"`

And if I try to authenticate with the previously read token I get the same message:

`> bq_auth(token = token)

> Waiting for authentication in browser...
> Press Esc/Ctrl + C to abort
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found
> /usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found
> xdg-open: no method available for opening 'https://accounts.google.com/o/oauth2/auth?client_id=603366585132-0l3n5tr582q443rnomebdeeo0156b2bc.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fbigquery%20https%3A%2F%2Fwww.g
> oogleapis.com%2Fauth%........'

^C`

Could you help me out to solve this problem?

Thank you for your help!
Best,
Arben

**Comment by jennybc** [comment]
> Here are the steps that I have taken so far locally on my RStudio console:

From that description, I gather you have a service account token? If so, I don't recommend that workflow (even though I gather it's working for you). I think you should _do less_. So, either do this to tell bigrquery about this token:

```
library(bigrquery)
bq_auth(path = "/home/arben/Scripts/BigQuery/keyscarab-xxxxxxxxxxxxxxx.json")
```

or, even better, put that token in one of the places consulted for Application Default Credentials:

<https://gargle.r-lib.org/reference/credentials_app_default.html>

and let auth "just work", without every doing anything explicit in your code.

Again, I'm not suggesting that you, personally, call `gargle::credentials_app_default()` or `token_fetch()`. If you leave a service token in one of these places, `bq_auth()` will find it. Yes, that may mean you need to store the path to the JSON in an env var, such as `GOOGLE_APPLICATION_CREDENTIALS`.

---

> Here are the steps that I have taken on GCP:

Again, before we get into details, I'd ask that you first do _less_.

Users of bigrquery and similar packages shouldn't need to make any calls to gargle, specifically they shouldn't be making calls to `gargle::token_fetch()`. The user-facing function for auth is `bq_auth()` and, even then, many users shouldn't need to call it explicitly themselves.

Have you tried doing no explicit auth at all to see if the [GCE credential method](https://gargle.r-lib.org/reference/credentials_gce.html) "just works"?

Otherwise, I need confirmation re: the first point. Are you using a service account token?

**Comment by ArbenKqiku** [comment]
Thanks!

This solution worked:

`library(bigrquery)
bq_auth(path = "/home/arben/Scripts/BigQuery/keyscarab-xxxxxxxxxxxxxxx.json")`

However, I had to create a new service account token, when I try to use the older one, I got this error message:

> bq_auth(path = "/home/arben/Scripts/BigQuery/keyscarab-261009-2d0fc84e7b17.json")
createTcpServer: address already in use
Error: Can't get Google credentials.

**Comment by jennybc** [comment]
The tcp error has nothing to do with the token. It usually means some
process was sitting on a port. 

Glad things are working with the service account!

Are you also providing an explicit service account on GCP or is the automatic one working?

**Comment by ArbenKqiku** [comment]
Yes, I am also providing an explicit service account.
