### ISSUE TITLE
bq_table_download not uploading a large dataset into R? 5M+ rows

### ISSUE THREAD

**Issue by santic113** [r-dbi/bigrquery#412]
I am querying a table in Google BigQuery in RStudio. The dataset is 5M+ rows. I don't receive an error when I query/upload the data, in fact it mentions that all the rows uploaded as a data frame/

Code & Ouput: 

```
sql_string = "SELECT * FROM table"
df_base <- bq_project_query(billing, sql_string)
df_base <- bq_table_download(df_base, max_results = Inf, page_size = 1000000)
Downloading 5,219,696 rows in 6 pages.
```

When I View(df_base)  the 5,219,696 dataset shows but at row 89,086 all the data in my cells are blank

**Comment by santic113** [comment]
![image](https://user-images.githubusercontent.com/43589961/96631179-00313380-12e4-11eb-8dcb-398eb62966bd.png)

**Comment by michaelgrund** [comment]
Same problem here, however, in my case the requested data frame contains time series data. From a certain row number onwards only dates of format 1970-01-01 appear in the corresponding "Date" column and the remaining columns are either blank or contain zeros. Nevertheless, the dimension of the data frame is correct.

In order to probe the causes of this problem I used the deprecated way via `query_exec(...)` to download the data (same sql query as for the `bq_table_download` try) . Here everything is fine, the dates are correct as well as the content of the other columns.

**Comment by ben-barnes** [comment]
I've had this issue come up too, I've done a bit of investigation today and figured I should report what I've found so far.

My current hypothesis is that we're hitting the page size limit as described here: https://cloud.google.com/bigquery/docs/paging-results

My reasoning for that is:
* The tibble returned by `bq_table_download` contains the same number of rows as my source table in BigQuery
* However only N of those rows contain any data.

**Comment by mbconnor** [comment]
I've found this same thing.  It's very sensitive to the pagesize, a slight deviation too large or too small will result in missing data.  I have not found a good way to determine what the pagesize should be prior to attempting to the download (and failing with an incorrect guess at the page size).

This is a big deal to me, I'm trying to use this package in production because there are no other good solutions for BigQuery and R.

**Comment by ndiquattro** [comment]
I'm also running into this issue. It seems to be pretty serious, has anyone found a consistent workaround?

FWIW, here's a reprex:

``` r
library(bigrquery)
library(dplyr, warn.conflicts = TRUE)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

con <-
  bigrquery::dbConnect(
    bigrquery::bigquery(),
    project = "bigquery-public-data"
  )

df <-
  tbl(con, "chicago_taxi_trips.taxi_trips") %>% 
  head(2e6) %>% 
  collect(page_size = 100000)
#> Warning in as.integer.integer64(x): NAs produced by integer overflow

#> Warning in as.integer.integer64(x): NAs produced by integer overflow

df %>% 
  filter(unique_key == "")
#> # A tibble: 1,517,610 x 23
#>    unique_key taxi_id trip_start_timestamp trip_end_timestamp  trip_seconds
#>    <chr>      <chr>   <dttm>               <dttm>                     <int>
#>  1 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  2 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  3 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  4 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  5 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  6 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  7 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  8 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#>  9 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#> 10 ""         ""      1970-01-01 00:00:00  1970-01-01 00:00:00            0
#> # … with 1,517,600 more rows, and 18 more variables: trip_miles <dbl>,
#> #   pickup_census_tract <int>, dropoff_census_tract <int>,
#> #   pickup_community_area <int>, dropoff_community_area <int>, fare <dbl>,
#> #   tips <dbl>, tolls <dbl>, extras <dbl>, trip_total <dbl>,
#> #   payment_type <chr>, company <chr>, pickup_latitude <dbl>,
#> #   pickup_longitude <dbl>, pickup_location <chr>, dropoff_latitude <dbl>,
#> #   dropoff_longitude <dbl>, dropoff_location <chr>
```

<sup>Created on 2021-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by leemc-data-ed** [comment]
@ben-barnes it looks like you're exactly right, that is what appears to be happening. Seems like an error or at least a warning would be useful when this happens! I just submitted a PR that addresses this issue, at least making it more obvious to the user when there's a mismatch between the table length and the json and giving a suggestion for recourse in the documentation.

**Comment by hadley** [comment]
I don't think there's much point in making little fixes here. Unfortunately it looks like the entire `bq_download_pages()` needs to be rewritten because I clearly misunderstood how pagination worked. This is unfortunately going to decrease performance because we can no longer download pages in parallel, and will have to parse each result to get the next page. But it's better to be correct than fast!
